name = "blog-posts-notifier-cf"
main = "src/worker.ts"
compatibility_date = "2023-05-15"

[triggers]
crons = ["0 1 1 * *"] # 毎月月初10時(USTなので-9時間)

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "user_bindings"
database_id = "2c1555b2-57dd-4097-aefc-628bbe5e27d1"
